### ISSUE TITLE
Generate appx package "Package building error"

### ISSUE THREAD

**Issue by csoftdesign** [pwa-builder/pwabuilder-api#83]
**Describe the bug**
I tried yesterday and today to generate an appx package for the Windows Store.
I got an error ("Package building error") after clicking the button generate. 

The error message in my browser dev tool is:
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)"
https://pwabuilder-api-prod.azurewebsites.net/manifests/76d6daf6/appx

**To Reproduce**
1. Go to 'pwabuilder.com'
2. Enter 'https://talkbutler.azurewebsites.net/' and click on 'Start'
3. Click the button 'Build my PWA'
4. Then click the arrow button in the Windows box
5. Then click the 'Generate' button
6. Enter valid values (I can not publish my values here)
7. See error

**Expected behavior**
Generate output of the appx package for Windows Store.

**Screenshots**
--

**Additional info (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Browser Version [76]

**Additional context**
Before I tried to generate the appx package, I downloded the package to install it as a
sideload and it worked. But the last time I tested (about 3 days ago) I had to change a Path in the file test_install.ps1 to $appxmanifest = 'manifest\AppxManifest.xml', that I could install
the sideload. The original value is $appxmanifest = 'Appmanifest\AppxManifest.xml' or so and that do not work to install the Win 10 sideload.

**Comment by JonathanMH** [comment]
Hi!

I just wanted to mention that I'm getting the same issue even though the manifest seems to validate fine on the frontend.

Also there's something wrong with the state management and the redirect follow policy of the backend is not very transparent.

For the the state management: You can submit a URL (without a service worker), check out the validation messages, navigate back to the submission form and submit a URL (without a manifest) and it will give you full points, because the previous results are somehow cached.

For the redirect follow: There's not info on if the backend follows server side redirects or not.

**Comment by jranma** [comment]
Same probleme here, trying to build the appx for park-oh.ch
error message "Package building error"

**Comment by lee-leonardo** [comment]
Hey @jgw96, this issue looks a little stale, is this still relevant?

**Comment by JudahGabriel** [comment]
Folks, we're updating our Windows platform this month to make PWAs that use the new Chromium-based engine under the hood. We'll test your URLs against the new platform.

**Comment by JudahGabriel** [comment]
@csoftdesign can you file this bug [here at our main repo](https://github.com/pwa-builder/PWABuilder/issues)? It will receive more attention and care there. Thanks.
